[server]
headless = true
runOnSave = false
enableCORS = true
enableXsrfProtection = true

[theme]
base = "light"
primaryColor = "#03c75a"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f6f8fa"
textColor = "#111111"
font = "sans serif"
